import { AlertTriangle, ArrowLeft, ArrowRight, Clipboard, Download, FileText, RotateCcw, Save } from "lucide-react";
import { formats, levelDetails, mediaOptions, modalities, relationshipLevels } from "./data";
import { usePersonaStore } from "./store";
import { BuyerPersonaData } from "./types";
import { alerts, botiquinType, buildJson, deriveGains, derivePains, keywords, prescription, recommendedKpis, topicClusters, vitalSigns } from "./lib/recommendations";
import { copyJson, downloadJson, exportPdf } from "./lib/exports";

const logoHeader = "https://docroi.marketing/wp-content/uploads/2026/04/Logo_1_Doc_ROI.png";
const logoFooter = "https://docroi.marketing/wp-content/uploads/2026/05/Logo_Negro_DoC_ROI.jpg";
const heroBg = "https://docroi.marketing/wp-content/uploads/2026/05/Imagen1.png";
const steps = ["Bienvenida", "Identidad", "Necesidad", "Empatía", "Compra", "Pirámide", "Contenido", "Producto", "Marketing mix", "Canalidad", "Keywords", "Clusters", "KPIs", "Receta", "Entregables"];

type Updater = <K extends keyof BuyerPersonaData>(key: K, value: BuyerPersonaData[K]) => void;

function Field({ label, value, onChange, area, help }: { label: string; value: string; onChange: (value: string) => void; area?: boolean; help?: string }) {
  return <label className="field"><span>{label}</span>{area ? <textarea value={value} onChange={(event) => onChange(event.target.value)} rows={4} /> : <input value={value} onChange={(event) => onChange(event.target.value)} />}{help && <small>{help}</small>}</label>;
}

function Slider({ label, value, onChange, min = 1, max = 5 }: { label: string; value: number | null; onChange: (value: number) => void; min?: number; max?: number }) {
  return <label className="slider"><span>{label}<b>{value ?? "pendiente"}</b></span><input type="range" min={min} max={max} value={value ?? min} onChange={(event) => onChange(Number(event.target.value))} /></label>;
}

function MultiSelect({ title, options, selected, onChange }: { title: string; options: string[]; selected: string[]; onChange: (value: string[]) => void }) {
  return <div className="multi"><h4>{title}</h4><div className="chip-grid">{options.map((option) => <button className={selected.includes(option) ? "chip selected" : "chip"} key={option} type="button" onClick={() => onChange(selected.includes(option) ? selected.filter((item) => item !== option) : [...selected, option])}>{option}</button>)}</div></div>;
}

function DocRoiHeader() {
  return <header className="doc-header"><div className="container header-inner"><img src={logoHeader} alt="Doc ROI" /><nav><a href="#constructor">Constructor</a><a href="#diagnostico">Diagnóstico</a><a href="#exportacion">Exportar</a></nav></div></header>;
}

function HeroConnection() {
  return <section className="hero" style={{ backgroundImage: `linear-gradient(90deg, rgba(5,7,11,.96), rgba(0,59,92,.82)), url(${heroBg})` }}><div className="container hero-grid"><div><span className="eyebrow">Píldora Doc ROI · Buyer Persona</span><h1>Conexión Buyer Persona · Del perfil al JSON accionable</h1><p>Primero diagnosticamos. Después prescribimos. Convierte una hipótesis de cliente en ficha estratégica, keywords, topic clusters, KPIs y receta ejecutiva.</p><div className="hero-actions"><a className="primary-btn" href="#constructor">Iniciar diagnóstico</a><a className="ghost-btn" href="#ruta">Ver ruta</a></div></div><div className="objective-panel"><h2>Objetivo clínico</h2><p>Construir una hipótesis estratégica sobre cómo una persona necesita, busca, consume, decide y se relaciona con una propuesta de valor.</p><dl><div><dt>Nivel</dt><dd>Ejecutivo aplicado</dd></div><div><dt>Herramientas</dt><dd>JSON, PDF, clusters, KPIs</dd></div><div><dt>Resultado</dt><dd>Receta Doc ROI validable</dd></div></dl></div></div></section>;
}

function VitalSigns({ data }: { data: BuyerPersonaData }) {
  const signs = vitalSigns(data);
  return <section className="vitals">{Object.entries(signs).map(([label, value]) => <article className="vital" key={label}><span>{label}</span><strong>{value}</strong><div><i style={{ width: `${value}%` }} /></div></article>)}</section>;
}

function DiiipPath() {
  return <section className="diiip">{["Data", "Information", "Intelligence", "Insights", "Personalization"].map((item) => <div key={item}><span>{item}</span><p>{item === "Data" ? "respuestas brutas" : item === "Information" ? "ficha estructurada" : item === "Intelligence" ? "diagnóstico y canalidad" : item === "Insights" ? "riesgos y KPIs" : "journey y JSON"}</p></div>)}</section>;
}

function KaiFormulaBlock() {
  return <section className="kai"><span className="eyebrow dark">Marco estratégico KAI·ROI</span><strong>KAI_i* = φ_i · u_i · f_i · ψ_i · SPO_i · P_i · Γ_g(i),t</strong><p>Esta píldora no sustituye el cálculo completo KAI·ROI. Prepara una capa previa de inteligencia relacional para entender mejor a quién nos dirigimos, cómo consume, qué le duele, qué le motiva y cómo puede activarse el dato para generar relación, productividad y Customer Equity.</p></section>;
}

function BuyerPersonaCard({ data, compact = false }: { data: BuyerPersonaData; compact?: boolean }) {
  return <article className={compact ? "persona-card compact" : "persona-card"}><div className="avatar">{data.avatar || "BP"}</div><div><h3>{data.fictionalName || "Buyer Persona pendiente"}</h3><p>{data.shortDescription || "Hipótesis todavía en construcción."}</p><span>{data.digitalGeneration}</span></div></article>;
}

function StrategicAlertPanel({ data }: { data: BuyerPersonaData }) {
  const items = alerts(data);
  if (!items.length) return <div className="success-note">Sin alertas críticas. La hipótesis está preparada para revisión ejecutiva.</div>;
  return <div className="alerts">{items.map((item) => <div className="alert" key={item.title + item.body}><AlertTriangle size={18} /><div><strong>{item.title}</strong><p>{item.body}</p></div></div>)}</div>;
}

function ProgressBar({ currentStep }: { currentStep: number }) {
  return <div className="progress-wrap"><div className="progress-meta"><span>Paso {currentStep + 1} de {steps.length}</span><strong>{Math.round(((currentStep + 1) / steps.length) * 100)}%</strong></div><div className="progress-track"><div style={{ width: `${((currentStep + 1) / steps.length) * 100}%` }} /></div></div>;
}

function FormSection({ title, diagnosis, children }: { title: string; diagnosis: string; children: React.ReactNode }) {
  return <section className="form-section"><div className="section-kicker"><Save size={18} />Guardado local automático</div><h3>{title}</h3><p>{diagnosis}</p><div className="form-grid">{children}</div></section>;
}

function DerivedList({ title, items }: { title: string; items: string[] }) {
  return <div className="derived"><h4>{title}</h4>{items.length ? items.map((item) => <span key={item}>{item}</span>) : <em>pendiente</em>}</div>;
}

function BasicFields({ data, update }: { data: BuyerPersonaData; update: Updater }) {
  return <><Field label="Nombre del proyecto" value={data.projectName} onChange={(v) => update("projectName", v)} /><Field label="Unidad de trabajo o equipo" value={data.workUnit} onChange={(v) => update("workUnit", v)} /><Field label="Nombre del usuario" value={data.userName} onChange={(v) => update("userName", v)} /><Field label="Email opcional" value={data.email} onChange={(v) => update("email", v)} /><Field label="Producto, gama o producto estrella" value={data.product} onChange={(v) => update("product", v)} help="Sin producto no hay diagnóstico accionable." /><Field label="Sector" value={data.sector} onChange={(v) => update("sector", v)} /><Field label="Mercado" value={data.market} onChange={(v) => update("market", v)} /><Field label="Objetivo de negocio" value={data.businessGoal} onChange={(v) => update("businessGoal", v)} area /><Slider label="% aproximado de consumidores representados" value={data.coverage} min={1} max={100} onChange={(v) => update("coverage", v)} /><p className="teaching">Empieza por un Buyer Persona relevante. Repite el ejercicio hasta cubrir el 80%-90% de tus consumidores relevantes.</p></>;
}

function StepContent({ step, data, update }: { step: number; data: BuyerPersonaData; update: Updater }) {
  const setTrust = (key: keyof BuyerPersonaData["trustDistribution"], value: number) => update("trustDistribution", { ...data.trustDistribution, [key]: value });
  const setMix = (key: keyof BuyerPersonaData["marketingMix"], value: number) => update("marketingMix", { ...data.marketingMix, [key]: value });
  const setWeight = (level: string, value: number) => update("levelWeights", { ...data.levelWeights, [level]: value });
  const kw = keywords(data);
  const clusters = topicClusters(data);
  const kpis = recommendedKpis(data);
  const rx = prescription(data);

  if (step === 0) return <FormSection title="Preparación" diagnosis="Contexto mínimo para priorizar la hipótesis."><BasicFields data={data} update={update} /></FormSection>;
  if (step === 1) return <FormSection title="Identidad del Buyer Persona" diagnosis="Caracterización inicial y generación digital."><Field label="Nombre ficticio" value={data.fictionalName} onChange={(v) => update("fictionalName", v)} /><Field label="Descripción breve" value={data.shortDescription} onChange={(v) => update("shortDescription", v)} area /><div className="form-grid two"><Field label="Edad aproximada" value={data.ageRange} onChange={(v) => update("ageRange", v)} /><Field label="Género si procede" value={data.gender} onChange={(v) => update("gender", v)} /><Field label="Ubicación" value={data.location} onChange={(v) => update("location", v)} /><Field label="Nivel económico o gasto" value={data.economicStatus} onChange={(v) => update("economicStatus", v)} /><Field label="Rol profesional o consumo" value={data.role} onChange={(v) => update("role", v)} /><Field label="Nivel de decisión" value={data.decisionLevel} onChange={(v) => update("decisionLevel", v)} /></div><label className="field"><span>Generación digital</span><select value={data.digitalGeneration} onChange={(e) => update("digitalGeneration", e.target.value)}>{["Baby Boomer digital", "Generación X digital", "Millennial", "Generación Z", "Alpha emergente", "Profesional híbrido", "C-Level analógico-digital", "Usuario IA avanzado"].map((x) => <option key={x}>{x}</option>)}</select></label><Field label="Contexto personal/profesional" value={data.context} onChange={(v) => update("context", v)} area /></FormSection>;
  if (step === 2) return <FormSection title="Necesidad y valor" diagnosis="Dolor, valor esperado y disparadores de confianza."><Field label="Qué necesita resolver" value={data.needsToSolve} onChange={(v) => update("needsToSolve", v)} area /><Field label="Qué le preocupa" value={data.mainConcern} onChange={(v) => update("mainConcern", v)} area /><Field label="Qué desea conseguir" value={data.desiredGain} onChange={(v) => update("desiredGain", v)} area /><Field label="Qué riesgo quiere evitar" value={data.riskToAvoid} onChange={(v) => update("riskToAvoid", v)} area /><Field label="Qué valor espera recibir" value={data.expectedValue} onChange={(v) => update("expectedValue", v)} area /><Field label="Qué considera éxito" value={data.successCriteria} onChange={(v) => update("successCriteria", v)} area /><Field label="Qué le impide comprar" value={data.mainBarrier} onChange={(v) => update("mainBarrier", v)} area /><Field label="Qué le hace confiar" value={data.trustTrigger} onChange={(v) => update("trustTrigger", v)} area /></FormSection>;
  if (step === 3) return <FormSection title="Mapa de empatía" diagnosis="Extrae pains, gains, lenguaje y semillas de keyword."><Field label="¿Qué piensa y siente?" value={data.thinksAndFeels} onChange={(v) => update("thinksAndFeels", v)} area /><Field label="¿Qué escucha?" value={data.hears} onChange={(v) => update("hears", v)} area /><Field label="¿Qué ve?" value={data.sees} onChange={(v) => update("sees", v)} area /><Field label="¿Qué dice y hace?" value={data.saysAndDoes} onChange={(v) => update("saysAndDoes", v)} area /><Field label="¿Qué le frustra?" value={data.frustrations} onChange={(v) => update("frustrations", v)} area /><Field label="¿Qué le motiva?" value={data.motivations} onChange={(v) => update("motivations", v)} area /><DerivedList title="Pains detectados" items={derivePains(data)} /><DerivedList title="Gains detectados" items={deriveGains(data)} /></FormSection>;
  if (step === 4) return <FormSection title="Comportamiento de compra" diagnosis="Lectura RFM pedagógica y señales de riesgo."><div className="form-grid two"><Slider label="Última relación" value={data.recency} onChange={(v) => update("recency", v)} /><Slider label="Frecuencia" value={data.frequency} onChange={(v) => update("frequency", v)} /><Slider label="Monetización" value={data.monetization} onChange={(v) => update("monetization", v)} /><Slider label="Satisfacción" value={data.satisfaction} onChange={(v) => update("satisfaction", v)} /><Slider label="Sensibilidad precio" value={data.priceSensitivity} onChange={(v) => update("priceSensitivity", v)} /><Slider label="Urgencia" value={data.urgency} onChange={(v) => update("urgency", v)} /><Slider label="Confianza" value={data.confidenceNeed} onChange={(v) => update("confidenceNeed", v)} /><Slider label="Prueba social" value={data.socialProofNeed} onChange={(v) => update("socialProofNeed", v)} /></div></FormSection>;
  if (step === 5) return <FormSection title="Pirámide Evolutiva de Relación con el Dato" diagnosis="Madurez relacional y personalización viable."><label className="field"><span>Nivel principal</span><select value={data.primaryLevel} onChange={(e) => update("primaryLevel", e.target.value)}>{relationshipLevels.map((x) => <option key={x}>{x}</option>)}</select><small>{levelDetails[data.primaryLevel]}</small></label><MultiSelect title="Niveles secundarios" options={relationshipLevels} selected={data.secondaryLevels} onChange={(v) => update("secondaryLevels", v)} /><div className="form-grid two">{relationshipLevels.map((level) => <Slider key={level} label={`Peso ${level}`} value={data.levelWeights[level] ?? 0} min={0} max={100} onChange={(v) => setWeight(level, v)} />)}</div><Field label="Observaciones" value={data.pyramidNotes} onChange={(v) => update("pyramidNotes", v)} area /></FormSection>;
  if (step === 6) return <FormSection title="Contenido digital" diagnosis="Confianza, modalidades, formatos y temporalidad."><div className="form-grid three"><Slider label="Confianza marca" value={data.trustDistribution.brand} min={0} max={100} onChange={(v) => setTrust("brand", v)} /><Slider label="Confianza producto" value={data.trustDistribution.product} min={0} max={100} onChange={(v) => setTrust("product", v)} /><Slider label="Confianza experiencia" value={data.trustDistribution.experience} min={0} max={100} onChange={(v) => setTrust("experience", v)} /></div><MultiSelect title="Modalidades" options={modalities} selected={data.modalities} onChange={(v) => update("modalities", v)} /><MultiSelect title="Formatos" options={formats} selected={data.formats} onChange={(v) => update("formats", v)} /><MultiSelect title="Temporalidad" options={["síncrono", "asíncrono", "actualizable a corto plazo", "evergreen", "contenido educativo permanente", "contenido de lanzamiento", "contenido de comparación", "contenido de prueba social"]} selected={data.temporality} onChange={(v) => update("temporality", v)} /></FormSection>;
  if (step === 7) return <FormSection title="Clasificación del producto" diagnosis="Aspirina, Vitamina, Vacuna o Deseo Premium."><label className="field"><span>Percepción dominante</span><select value={data.productClassification} onChange={(e) => update("productClassification", e.target.value)}>{["Aspirina", "Vitamina", "Vacuna", "Deseo Premium"].map((x) => <option key={x}>{x}</option>)}</select></label><Field label="¿Qué pasa si el cliente no compra?" value={data.noBuyConsequence} onChange={(v) => update("noBuyConsequence", v)} area /><Slider label="Urgencia percibida" value={data.perceivedUrgency} onChange={(v) => update("perceivedUrgency", v)} /><label className="field"><span>Lógica de compra</span><select value={data.purchaseLogic} onChange={(e) => update("purchaseLogic", e.target.value)}>{["racional", "emocional", "urgente", "aspiracional"].map((x) => <option key={x}>{x}</option>)}</select></label></FormSection>;
  if (step === 8) return <FormSection title="Marketing mix" diagnosis="Política dominante y riesgo de comunicación."><div className="form-grid two"><Slider label="Producto" value={data.marketingMix.product} onChange={(v) => setMix("product", v)} /><Slider label="Precio" value={data.marketingMix.price} onChange={(v) => setMix("price", v)} /><Slider label="Punto/red de venta" value={data.marketingMix.place} onChange={(v) => setMix("place", v)} /><Slider label="Promoción" value={data.marketingMix.promotion} onChange={(v) => setMix("promotion", v)} /></div></FormSection>;
  if (step === 9) return <FormSection title="Arquitectura relacional de canalidad" diagnosis="Terminales, medios, soportes, formatos e intención."><MultiSelect title="Terminales" options={["Small Screen", "Medium Screen", "Big Screen", "Multidispositivo"]} selected={data.terminals} onChange={(v) => update("terminals", v)} /><MultiSelect title="Medios" options={mediaOptions} selected={data.media} onChange={(v) => update("media", v)} /><MultiSelect title="Soportes" options={["LinkedIn", "Instagram", "TikTok", "YouTube", "newsletter", "landing pages", "blog", "ROI calculators", "ChatGPT", "Gemini", "Claude", "agentes IA"]} selected={data.supports} onChange={(v) => update("supports", v)} /><MultiSelect title="Intención relacional" options={["aprender", "resolver", "comparar", "comprar", "inspirarse", "autoridad profesional", "automatizar", "delegar", "mejorar productividad"]} selected={data.intentions} onChange={(v) => update("intentions", v)} /></FormSection>;
  if (step === 10) return <FormSection title="Keywords estratégicas" diagnosis="Hipótesis SEO y relacional generada desde el Buyer Persona."><p className="teaching">Esta simulación no sustituye a una herramienta SEO profesional.</p><div className="panel-grid">{Object.entries(kw).map(([group, items]) => <article className="mini-panel" key={group}><h4>{group}</h4>{items.map((item) => <span key={item}>{item}</span>)}</article>)}</div></FormSection>;
  if (step === 11) return <FormSection title="Topic clusters" diagnosis="Temas pilar conectados con dolores, ganancias, formatos y canalidad."><div className="panel-grid">{clusters.map((cluster) => <article className="mini-panel" key={cluster.pillar_topic}><h4>{cluster.pillar_topic}</h4><p>{cluster.subtopics.join(" · ")}</p><span>{cluster.journey_stage}</span><span>{cluster.recommended_kpis.join(", ")}</span></article>)}</div></FormSection>;
  if (step === 12) return <FormSection title="KPIs recomendados" diagnosis="Indicadores por madurez, canalidad e intención."><div className="panel-grid">{Object.entries(kpis).map(([group, items]) => <article className="mini-panel" key={group}><h4>{group}</h4>{items.map((item) => <span key={item}>{item}</span>)}</article>)}</div></FormSection>;
  if (step === 13) return <FormSection title="Diagnóstico Doc ROI" diagnosis="Receta final con metodología DIIIP."><BuyerPersonaCard data={data} /><div className="prescription">{Object.entries(rx).map(([key, value]) => <article key={key}><span>{key}</span><p>{value}</p></article>)}</div></FormSection>;
  return <FormSection title="Entregables" diagnosis="Ficha visual, JSON, PDF y prompts listos para activar."><div className="export-grid" id="exportacion"><button className="primary-btn" type="button" onClick={() => downloadJson(data)}><Download size={18} />Descargar JSON</button><button className="secondary-btn" type="button" onClick={() => copyJson(data)}><Clipboard size={18} />Copiar JSON</button><button className="secondary-btn" type="button" onClick={() => exportPdf(data)}><FileText size={18} />Descargar PDF</button></div><pre className="json-viewer"><code>{JSON.stringify(buildJson(data), null, 2)}</code></pre></FormSection>;
}

function StepWizard() {
  const { data, currentStep, update, setStep, reset } = usePersonaStore();
  return <section className="builder container" id="constructor"><div className="builder-head"><span className="eyebrow">Constructor guiado</span><h2>{steps[currentStep]}</h2><p>Una buena ficha debe servir para decidir contenidos, canales, mensajes, automatizaciones y KPIs.</p></div><ProgressBar currentStep={currentStep} /><div className="builder-grid"><aside className="step-list">{steps.map((step, index) => <button className={index === currentStep ? "active" : ""} type="button" key={step} onClick={() => setStep(index)}><span>{index + 1}</span>{step}</button>)}</aside><main className="wizard-card"><StepContent step={currentStep} data={data} update={update} /><div className="wizard-actions"><button className="secondary-btn" type="button" onClick={() => setStep(currentStep - 1)} disabled={currentStep === 0}><ArrowLeft size={18} />Anterior</button><button className="secondary-btn" type="button" onClick={reset}><RotateCcw size={18} />Reiniciar</button><button className="primary-btn small" type="button" onClick={() => setStep(currentStep + 1)} disabled={currentStep === steps.length - 1}>Siguiente<ArrowRight size={18} /></button></div></main><aside className="summary-panel"><h3>Resumen parcial</h3><BuyerPersonaCard data={data} compact /><VitalSigns data={data} /><StrategicAlertPanel data={data} /></aside></div></section>;
}

function FAQBlock() {
  return <section className="faq container"><span className="eyebrow">FAQ</span><h2>Notas metodológicas</h2><details open><summary>¿Es un cálculo financiero oficial?</summary><p>No. Los signos vitales son indicadores pedagógicos para orientar decisión, no sustituyen análisis financiero, CRM ni analítica real.</p></details><details><summary>¿Qué pasa si faltan datos?</summary><p>La app usa pendiente, no informado o requiere validación. Nunca convierte datos desconocidos en cero.</p></details><details><summary>¿Puede conectarse a IA o automatización?</summary><p>Sí. El JSON está preparado para flujos con OpenAI, Gemini, Claude, n8n, Sheets, Notion, CRM, KAIloop o neXus Kukulcán.</p></details></section>;
}

function DocRoiFooter() {
  return <footer className="footer"><div className="container footer-inner"><img src={logoFooter} alt="Doc ROI" /><p>Doc ROI · Píldora formativa. Las recomendaciones son hipótesis estratégicas y deben validarse con datos reales.</p></div></footer>;
}

export function App() {
  const data = usePersonaStore((state) => state.data);
  return <div className="app-shell"><DocRoiHeader /><HeroConnection /><main><section className="route container" id="ruta"><span className="eyebrow">Ruta Connection</span><h2>Del síntoma al entregable</h2><DiiipPath /><div className="route-grid"><article className="dark-card"><span className="eyebrow dark">Botiquín Doc ROI</span><h3>{botiquinType(data)}</h3><p>Intervención recomendada según madurez, urgencia y capacidad de activación.</p></article><KaiFormulaBlock /></div></section><StepWizard /><section className="diagnosis container" id="diagnostico"><span className="eyebrow">Vista ejecutiva</span><h2>Ficha visual y receta</h2><div className="diagnosis-grid"><BuyerPersonaCard data={data} /><VitalSigns data={data} /><FormSection title="Receta Doc ROI" diagnosis="Diagnóstico final accionable."><div className="prescription">{Object.entries(prescription(data)).map(([key, value]) => <article key={key}><span>{key}</span><p>{value}</p></article>)}</div></FormSection></div></section><FAQBlock /></main><DocRoiFooter /></div>;
}
