import { BuyerPersonaData } from "./types";

export const initialData: BuyerPersonaData = {
  projectName: "",
  workUnit: "",
  userName: "",
  email: "",
  product: "",
  starProduct: "",
  sector: "",
  market: "",
  businessGoal: "",
  coverage: 25,
  fictionalName: "",
  shortDescription: "",
  ageRange: "",
  gender: "",
  location: "",
  economicStatus: "",
  role: "",
  decisionLevel: "",
  context: "",
  productsPerYear: "",
  mainCondition: "",
  digitalGeneration: "Profesional híbrido",
  avatar: "BP",
  avatarUrl: "",
  needsToSolve: "",
  mainConcern: "",
  desiredGain: "",
  riskToAvoid: "",
  expectedValue: "",
  successCriteria: "",
  mainBarrier: "",
  trustTrigger: "",
  thinksAndFeels: "",
  hears: "",
  sees: "",
  saysAndDoes: "",
  frustrations: "",
  motivations: "",
  recency: 3,
  frequency: 3,
  monetization: 3,
  satisfaction: 3,
  priceSensitivity: 3,
  urgency: 3,
  confidenceNeed: 3,
  socialProofNeed: 3,
  primaryLevel: "Información",
  secondaryLevels: ["Interacción"],
  levelWeights: { Información: 60, Interacción: 40 },
  pyramidNotes: "",
  trustDistribution: { brand: 34, product: 33, experience: 33 },
  modalities: ["texto", "PDF", "demo"],
  formats: ["blog", "caso de uso", "calculadora ROI"],
  temporality: ["evergreen", "contenido educativo permanente"],
  productClassification: "Vitamina",
  noBuyConsequence: "",
  perceivedUrgency: 3,
  purchaseLogic: "racional",
  marketingMix: { product: 4, price: 3, place: 3, promotion: 4 },
  terminals: ["Small Screen", "Medium Screen"],
  media: ["Web", "Email", "IA conversacional"],
  supports: ["landing pages", "newsletter", "ChatGPT"],
  channelFormats: ["artículos", "simuladores", "plantillas"],
  intentions: ["aprender", "comparar", "mejorar productividad"],
};

export const digitalGenerations = {
  "Baby Boomer digital": { traits: ["Busca claridad", "Valora autoridad", "Prefiere confianza previa"], channels: ["email", "web", "eventos digitales"], autonomy: "Media" },
  "Generación X digital": { traits: ["Compara antes de decidir", "Valora eficiencia", "Responde a prueba social"], channels: ["web", "LinkedIn", "email"], autonomy: "Media-alta" },
  Millennial: { traits: ["Investiga rápido", "Es sensible a experiencia", "Espera autoservicio"], channels: ["redes sociales", "web", "podcasts"], autonomy: "Alta" },
  "Generación Z": { traits: ["Consume visual", "Busca autenticidad", "Decide desde comunidad"], channels: ["TikTok", "Instagram", "YouTube"], autonomy: "Alta" },
  "Alpha emergente": { traits: ["Interactiva", "Nativa de IA", "Espera inmediatez"], channels: ["apps", "video", "IA conversacional"], autonomy: "Emergente" },
  "Profesional híbrido": { traits: ["Combina criterio humano y digital", "Necesita síntesis", "Valora herramientas accionables"], channels: ["LinkedIn", "email", "web", "IA conversacional"], autonomy: "Alta" },
  "C-Level analógico-digital": { traits: ["Busca impacto ejecutivo", "Poco tiempo", "Exige evidencia"], channels: ["LinkedIn", "email", "eventos", "informes PDF"], autonomy: "Media" },
  "Usuario IA avanzado": { traits: ["Automatiza", "Itera rápido", "Busca integración"], channels: ["IA conversacional", "comunidades", "herramientas"], autonomy: "Muy alta" },
};

export const relationshipLevels = ["Acceso", "Información", "Interacción", "Transacción", "Relación", "Experiencia", "Influencia", "Autogestión"];

export const levelDetails: Record<string, string> = {
  Acceso: "Necesita encontrar y entender lo básico antes de avanzar.",
  Información: "Busca claridad, argumentos y reducción de incertidumbre.",
  Interacción: "Está dispuesto a responder, preguntar o probar.",
  Transacción: "Evalúa compra, conversión, coste y confianza.",
  Relación: "Puede sostener recurrencia, retención y seguimiento.",
  Experiencia: "Valora satisfacción, recuerdo y vivencia completa.",
  Influencia: "Puede recomendar, crear prueba social o activar comunidad.",
  Autogestión: "Quiere operar con autonomía, herramientas e integraciones.",
};

export const modalities = ["vídeo", "imagen", "texto", "audio", "interactivo", "PDF", "demo", "simulador", "calculadora", "webinar", "podcast", "plantilla", "caso práctico", "whitepaper", "checklist", "tutorial", "herramienta IA"];
export const formats = ["post", "carrusel", "infografía", "short", "reel", "TikTok", "vídeo largo", "foto", "newsletter", "email nurture", "landing", "blog", "hilo", "webinar", "podcast", "demo", "simulador", "calculadora ROI", "plantilla descargable", "caso de uso", "informe PDF"];
export const mediaOptions = ["Email", "Web", "Redes sociales", "Canales audiovisuales", "Marketplaces", "Aplicaciones móviles", "Plataformas formativas", "Mensajería instantánea", "IA conversacional", "Eventos digitales", "Podcasts", "Comunidades digitales"];
