import { keywords, recommendedKpis, topicClusters } from "./lib/recommendations";
import { usePersonaStore } from "./store";

const styleId = "docroi-editable-strategy-safe-style";
const storageKey = "docroi-buyer-persona-strategy-selections-v2";
let scheduled = false;

type State = { signature: string; keywords: string[]; keywordCustom: Record<string, string[]>; clusters: string[]; kpis: string[]; kpiCustom: Record<string, string[]> };
type Group = { key: string; title: string; items: string[] };
type Cluster = { id: string; title: string; subtopics: string[]; keywords: string[]; stage: string };

function esc(value: unknown) { return String(value ?? "").replace(/[&<>"]/g, (c) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;" }[c] || c)); }
function slug(value: string) { return value.toLowerCase().normalize("NFD").replace(/[\u0300-\u036f]/g, "").replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, "") || "item"; }
function unique(items: string[]) { return Array.from(new Set(items.map((item) => item.trim()).filter(Boolean))); }
function data() { return usePersonaStore.getState().data; }
function signature() { const d = data(); return JSON.stringify({ product: d.product, sector: d.sector, role: d.role, goal: d.businessGoal, need: d.needsToSolve, level: d.primaryLevel, media: d.media, formats: d.formats, name: d.fictionalName }); }

function kwLabel(key: string) { return ({ informational: "Informativas", comparative: "Comparativas", transactional: "Transaccionales", navigational: "Navegacionales", relational: "Relacionales", experiential: "Experienciales", autonomy: "Autogestión / IA", long_tail: "Long tail estratégica" } as Record<string, string>)[key] || key; }
function kpiLabel(key: string) { return ({ awareness: "Awareness", engagement: "Engagement", conversion: "Conversión", relationship: "Relación", loyalty: "Fidelización", experience: "Experiencia", influence: "Influencia", autonomy: "Autogestión" } as Record<string, string>)[key] || key; }
function kwGroups(): Group[] { return Object.entries(keywords(data())).map(([key, items]) => ({ key, title: kwLabel(key), items: unique(items) })); }
function kpiGroups(): Group[] { return Object.entries(recommendedKpis(data())).map(([key, items]) => ({ key, title: kpiLabel(key), items: unique(items) })); }
function clusters(): Cluster[] { const d = data(); const base = topicClusters(d).map((c, i) => ({ id: `c-${i}-${slug(c.pillar_topic)}`, title: c.pillar_topic, subtopics: c.subtopics, keywords: c.keywords, stage: c.journey_stage })); return [...base, { id: `c-content-${slug(d.product || "producto")}`, title: `Contenido educativo para ${d.product || "producto"}`, subtopics: ["preguntas frecuentes", "objeciones", "guías", "casos de uso"], keywords: d.formats.slice(0, 3).length ? d.formats.slice(0, 3) : ["guía", "demo", "caso de uso"], stage: "aprendizaje y confianza" }, { id: `c-channel-${slug(d.fictionalName || "buyer-persona")}`, title: `Canalidad y conversión para ${d.fictionalName || "Buyer Persona"}`, subtopics: ["terminal", "medio", "soporte", "formato", "seguimiento"], keywords: d.media.slice(0, 3).length ? d.media.slice(0, 3) : ["canalidad", "confianza", "conversión"], stage: d.needsToSolve || "necesidad principal" }].slice(0, 4); }

function defaults(): State { return { signature: signature(), keywords: kwGroups().flatMap((g) => g.items).slice(0, 14), keywordCustom: {}, clusters: clusters().slice(0, 2).map((c) => c.id), kpis: kpiGroups().flatMap((g) => g.items).slice(0, 14), kpiCustom: {} }; }
function load(): State { try { const parsed = JSON.parse(localStorage.getItem(storageKey) || "null") as State | null; if (parsed?.signature === signature()) return parsed; } catch {} const state = defaults(); save(state); return state; }
function save(state: State) { localStorage.setItem(storageKey, JSON.stringify(state)); }
function toggle(list: string[], item: string) { return list.includes(item) ? list.filter((x) => x !== item) : unique([...list, item]); }
function addCustom(kind: "keyword" | "kpi", group: string, raw: string) { const item = raw.trim(); if (!item) return; const state = load(); if (kind === "keyword") { state.keywordCustom[group] = unique([...(state.keywordCustom[group] || []), item]); state.keywords = unique([...state.keywords, item]); } else { state.kpiCustom[group] = unique([...(state.kpiCustom[group] || []), item]); state.kpis = unique([...state.kpis, item]); } save(state); }

function installStyles() { if (document.getElementById(styleId)) return; const style = document.createElement("style"); style.id = styleId; style.textContent = `
  .docroi-editable-strategy{grid-column:1/-1;display:grid;gap:16px;text-align:left}.docroi-editable-strategy-head,.docroi-editable-group,.docroi-cluster-card{border:1px solid #dce7ef;border-radius:18px;background:#fff;padding:16px;display:grid;gap:10px}.docroi-editable-strategy-head{background:#f8fafc}.docroi-editable-strategy-head span{display:inline-flex;width:fit-content;border-radius:999px;padding:7px 10px;background:#eaf6fb;color:#003b5c;font-size:10px;font-weight:950;text-transform:uppercase;letter-spacing:.05em}.docroi-editable-strategy-head strong{color:#003b5c;font-size:22px;line-height:1.08;font-weight:950}.docroi-editable-strategy-head p,.docroi-cluster-card p{margin:0;color:#475569!important;font-size:14px!important;line-height:1.55!important}.docroi-editable-group h4{margin:0;color:#003b5c;font-size:18px;font-weight:950}.docroi-editable-chips{display:flex;flex-wrap:wrap;gap:8px}.docroi-editable-chip{border:1px solid #dce7ef;border-radius:999px;background:#fff;color:#0f172a;padding:9px 11px;cursor:pointer;font-size:12px;font-weight:850}.docroi-editable-chip.active{background:#003b5c;border-color:#003b5c;color:#fff}.docroi-other-row{display:flex;flex-wrap:wrap;gap:8px}.docroi-other-row input{min-height:42px;border:1px solid #dce7ef;border-radius:999px;padding:0 13px;flex:1 1 220px}.docroi-other-row button{min-height:42px;border:0;border-radius:999px;background:#eaf6fb;color:#003b5c;padding:0 13px;font-size:12px;font-weight:950;cursor:pointer}.docroi-cluster-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:12px}.docroi-cluster-card.active{border-color:#003b5c;box-shadow:inset 0 0 0 2px rgba(0,59,92,.16)}.docroi-cluster-card label{display:flex;gap:9px;align-items:center;color:#003b5c;font-size:18px;line-height:1.1;font-weight:950;cursor:pointer}.docroi-cluster-card input{width:18px;height:18px;accent-color:#003b5c}.docroi-cluster-card small{color:#64748b;font-size:11px;font-weight:850}.panel-grid.docroi-original-hidden{display:none!important}@media(max-width:800px){.docroi-cluster-grid{grid-template-columns:1fr}}
`; document.head.appendChild(style); }
function stepTitle() { return (document.querySelector(".builder-head h2")?.textContent || "").trim(); }
function formGrid() { return document.querySelector<HTMLElement>(".wizard-card .form-section .form-grid"); }
function hideOriginal() { formGrid()?.querySelector(".panel-grid")?.classList.add("docroi-original-hidden"); }
function setHtml(kind: string, html: string, sig: string) { const grid = formGrid(); if (!grid) return; const existing = grid.querySelector<HTMLElement>(`[data-docroi-editable-strategy="${kind}"]`); if (existing?.dataset.sig === sig) return; if (existing) existing.outerHTML = html; else grid.insertAdjacentHTML("beforeend", html); }

function chipGroup(group: Group, selected: string[], custom: string[], kind: "keyword" | "kpi") { const items = unique([...group.items, ...custom]); return `<article class="docroi-editable-group"><h4>${esc(group.title)}</h4><div class="docroi-editable-chips">${items.map((item) => `<button type="button" class="docroi-editable-chip ${selected.includes(item) ? "active" : ""}" data-kind="${kind}" data-value="${esc(item)}">${esc(item)}</button>`).join("")}</div><div class="docroi-other-row"><input data-other-input="${kind}" data-group="${esc(group.key)}" placeholder="${kind === "keyword" ? "Otra keyword" : "Otro KPI"}"><button type="button" data-add-other="${kind}" data-group="${esc(group.key)}">Añadir otro</button></div></article>`; }
function renderKeywords() { hideOriginal(); const s = load(); const sig = JSON.stringify({ t: "kw", s }); const html = `<section class="docroi-editable-strategy" data-docroi-editable-strategy="keywords" data-sig="${esc(sig)}"><header class="docroi-editable-strategy-head"><span>Propuesta editable</span><strong>Hemos obtenido estas keywords como aproximación inicial</strong><p>Selecciona las que consideres más oportunas. Puedes activar, desactivar o añadir otras etiquetas. Lo seleccionado aparecerá en la Ficha Buyer Persona final.</p></header>${kwGroups().map((g) => chipGroup(g, s.keywords, s.keywordCustom[g.key] || [], "keyword")).join("")}</section>`; setHtml("keywords", html, sig); }
function renderKpis() { hideOriginal(); const s = load(); const sig = JSON.stringify({ t: "kpi", s }); const html = `<section class="docroi-editable-strategy" data-docroi-editable-strategy="kpis" data-sig="${esc(sig)}"><header class="docroi-editable-strategy-head"><span>Propuesta editable</span><strong>Hemos obtenido estos KPIs recomendados como aproximación inicial</strong><p>Activa los indicadores que quieras llevar a seguimiento. Puedes añadir otros por categoría. Lo seleccionado aparecerá en la Ficha Buyer Persona final.</p></header>${kpiGroups().map((g) => chipGroup(g, s.kpis, s.kpiCustom[g.key] || [], "kpi")).join("")}</section>`; setHtml("kpis", html, sig); }
function renderClusters() { hideOriginal(); const s = load(); const opts = clusters(); const sig = JSON.stringify({ t: "clusters", c: s.clusters, opts }); const html = `<section class="docroi-editable-strategy" data-docroi-editable-strategy="clusters" data-sig="${esc(sig)}"><header class="docroi-editable-strategy-head"><span>Checklist estratégico</span><strong>Hemos obtenido estos topic clusters como aproximación inicial</strong><p>Selecciona los clusters con los que estás de acuerdo. Aquí no se edita: se valida qué territorios temáticos pasan a la ficha final.</p></header><div class="docroi-cluster-grid">${opts.map((c) => `<article class="docroi-cluster-card ${s.clusters.includes(c.id) ? "active" : ""}"><label><input type="checkbox" ${s.clusters.includes(c.id) ? "checked" : ""} data-cluster="${esc(c.id)}">${esc(c.title)}</label><p>${esc(c.subtopics.join(" · "))}</p><small>${esc(c.stage)} · ${esc(c.keywords.join(" · "))}</small></article>`).join("")}</div></section>`; setHtml("clusters", html, sig); }
function selectedClusters() { const s = load(); return clusters().filter((c) => s.clusters.includes(c.id)); }
function pills(items: string[]) { return items.map((item) => `<span>${esc(item)}</span>`).join("") || '<span class="empty">pendiente</span>'; }
function renderFinal() { const dossier = document.querySelector('[data-docroi-final-dossier="1"]'); if (!dossier) return; const s = load(); const sig = JSON.stringify(s); if ((dossier as HTMLElement).dataset.strategySig === sig) return; (dossier as HTMLElement).dataset.strategySig = sig; const cards = Array.from(dossier.querySelectorAll<HTMLElement>(".dossier-card")); const kwCard = cards.find((card) => /11\.\s*Keywords/i.test(card.querySelector("h4")?.textContent || "")); if (kwCard) kwCard.innerHTML = `<h4>11. Keywords estratégicas seleccionadas</h4><p>Keywords validadas por el alumno a partir de la propuesta generada.</p><div class="dossier-pills">${pills(s.keywords)}</div>`; const cCard = cards.find((card) => /12\.\s*Topic/i.test(card.querySelector("h4")?.textContent || "")); const chosen = selectedClusters(); if (cCard) cCard.innerHTML = `<h4>12. Topic clusters seleccionados</h4><div class="dossier-branches">${chosen.map((c) => `<article><b>${esc(c.title)}</b><p>${esc(c.subtopics.join(" · "))}</p><p>${esc(c.stage)}</p></article>`).join("") || '<article><b>Pendiente</b><p>No hay clusters seleccionados.</p></article>'}</div>`; const kpiCard = cards.find((card) => /13\.\s*KPIs/i.test(card.querySelector("h4")?.textContent || "")); if (kpiCard) kpiCard.innerHTML = `<h4>13. KPIs seleccionados</h4><p>Indicadores validados para seguimiento del Buyer Persona.</p><div class="dossier-pills">${pills(s.kpis)}</div>`; }

function clickHandler(event: MouseEvent) { const el = event.target as HTMLElement | null; const chip = el?.closest<HTMLButtonElement>("[data-kind][data-value]"); if (chip) { const s = load(); const v = chip.dataset.value || ""; if (chip.dataset.kind === "keyword") s.keywords = toggle(s.keywords, v); if (chip.dataset.kind === "kpi") s.kpis = toggle(s.kpis, v); save(s); schedule(); return; } const add = el?.closest<HTMLButtonElement>("[data-add-other]"); if (add) { const kind = add.dataset.addOther === "kpi" ? "kpi" : "keyword"; const group = add.dataset.group || "otros"; const input = document.querySelector<HTMLInputElement>(`input[data-other-input="${kind}"][data-group="${CSS.escape(group)}"]`); addCustom(kind, group, input?.value || ""); if (input) input.value = ""; schedule(); return; } const cluster = el?.closest<HTMLInputElement>("[data-cluster]"); if (cluster) { const s = load(); s.clusters = toggle(s.clusters, cluster.dataset.cluster || ""); save(s); schedule(); } }
function keyHandler(event: KeyboardEvent) { if (event.key !== "Enter") return; const input = event.target instanceof HTMLInputElement ? event.target : null; const kind = input?.dataset.otherInput; if (!kind) return; event.preventDefault(); addCustom(kind === "kpi" ? "kpi" : "keyword", input.dataset.group || "otros", input.value); input.value = ""; schedule(); }
function apply() { scheduled = false; installStyles(); const title = stepTitle(); if (/keywords/i.test(title)) renderKeywords(); else document.querySelector('[data-docroi-editable-strategy="keywords"]')?.remove(); if (/clusters/i.test(title)) renderClusters(); else document.querySelector('[data-docroi-editable-strategy="clusters"]')?.remove(); if (/kpis/i.test(title)) renderKpis(); else document.querySelector('[data-docroi-editable-strategy="kpis"]')?.remove(); renderFinal(); }
function schedule() { if (scheduled) return; scheduled = true; requestAnimationFrame(apply); }

if (typeof window !== "undefined") { window.addEventListener("DOMContentLoaded", () => { schedule(); document.addEventListener("click", clickHandler, true); document.addEventListener("keydown", keyHandler, true); const root = document.getElementById("root") || document.body; new MutationObserver(schedule).observe(root, { childList: true, subtree: true, characterData: true }); usePersonaStore.subscribe(schedule); }); }
export {};
