export type Score = number | null;

export type BuyerPersonaData = {
  projectName: string;
  workUnit: string;
  userName: string;
  email: string;
  product: string;
  starProduct: string;
  sector: string;
  market: string;
  businessGoal: string;
  coverage: number;
  fictionalName: string;
  shortDescription: string;
  ageRange: string;
  gender: string;
  location: string;
  economicStatus: string;
  role: string;
  decisionLevel: string;
  context: string;
  productsPerYear: string;
  mainCondition: string;
  digitalGeneration: string;
  avatar: string;
  needsToSolve: string;
  mainConcern: string;
  desiredGain: string;
  riskToAvoid: string;
  expectedValue: string;
  successCriteria: string;
  mainBarrier: string;
  trustTrigger: string;
  thinksAndFeels: string;
  hears: string;
  sees: string;
  saysAndDoes: string;
  frustrations: string;
  motivations: string;
  recency: Score;
  frequency: Score;
  monetization: Score;
  satisfaction: Score;
  priceSensitivity: Score;
  urgency: Score;
  confidenceNeed: Score;
  socialProofNeed: Score;
  primaryLevel: string;
  secondaryLevels: string[];
  levelWeights: Record<string, number>;
  pyramidNotes: string;
  trustDistribution: { brand: number; product: number; experience: number };
  modalities: string[];
  formats: string[];
  temporality: string[];
  productClassification: string;
  noBuyConsequence: string;
  perceivedUrgency: Score;
  purchaseLogic: string;
  marketingMix: { product: number; price: number; place: number; promotion: number };
  terminals: string[];
  media: string[];
  supports: string[];
  channelFormats: string[];
  intentions: string[];
};

export type StrategicAlert = { title: string; body: string };

export type TopicCluster = {
  pillar_topic: string;
  subtopics: string[];
  keywords: string[];
  connected_pains: string[];
  connected_gains: string[];
  recommended_formats: string[];
  recommended_channels: string[];
  recommended_kpis: string[];
  journey_stage: string;
};
